site_name: AI Services Documentation

# Uncomment the repo_url if GH Icon is needed on docs page
# repo_url: https://github.ibm.com/project-ai-services/project-ai-services

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - Home: index.md
  - Installation: installation.md
  - CLI Reference:
    - Overview: commands.md
    - Commands:
      - application: commands/application.md
      - application subcommands:
        - create: commands/application/create.md
        - delete: commands/application/delete.md
        - image: commands/application/image.md
        - info: commands/application/info.md
        - model: commands/application/model.md
        - ps: commands/application/ps.md
        - start: commands/application/start.md
        - stop: commands/application/stop.md
        - templates: commands/application/templates.md
      - completion: commands/completion.md
      - help: commands/help.md
      - version: commands/version.md
  - Chatbot: chatbot.md
  - Tutorials: 
    - Creating an application: tutorials/create-app.md
    - Installing in air-gapped environment: tutorials/airgapped-env.md
  - Limitations: limitations.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
